apiVersion: v1
kind: Service
metadata:
  name: argocd-project-svc
  namespace: argocd-project
spec:
  selector:
    app: argocdproject
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8181
      nodePort: 30000
  type: LoadBalancer
